[package]
name = "examination"
version = "0.0.1"
entrypoint = "src/lib.typ"
authors = [
  "Clemens Koza <https://github.com/SillyFreak/>"
]
license = "MIT"
description = "A library for building exams, tests, etc. with Typst"
repository = "https://github.com/SillyFreak/typst-packages/examination"
keywords = []
# compiler = ""
exclude = [
  # manual and gallery are not needed in the final package
  "manual.typ",
  "manual.pdf",
  "gallery/*",
]
